### ISSUE TITLE
年月日显示间距有问题

### ISSUE THREAD

**Issue by cxx3344** [CXTretar/CXDatePickerView#12]
`- (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView {
    ///此处可以去除
    ///[self addLabelWithName:self.manager.unitArray];
    return self.manager.unitArray.count;
}
`
在赋值时使用下面的方式
`
-(UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view {
  //..........
   title = [NSString stringWithFormat:@"%@%@",title,self.manager.unitArray[component]];
  //..........
}
`

**Comment by cxx3344** [comment]
是否可以提供,选中日期颜色,字体设置,与未选中的不一致

**Comment by CXTretar** [comment]
@cxx3344 
谢谢提醒，在 0.2.5 版本中：
1、日期单位的显示间距我做了微调。
2、新增加了 3 种日期单位的显示样式，你可以自己选择所需样式。
3、新增加了选中日期以及日期单位的字体，颜色单独属性设置，你可以自定义配置。
