### ISSUE TITLE
帮我在 日时分那里增加可以选择 0日0时0分的可以不、

### ISSUE THREAD

**Issue by jasonpakio** [CXTretar/CXDatePickerView#2]
因为项目需求 需要有  00-00-00   dd-hh-mm

**Comment by CXTretar** [comment]
00-00-00 dd-hh-mm 指的是哪里的显示，日期输出格式可以自己设置，亲

**Comment by CXTretar** [comment]
哦，我懂了，你是想增加 00 这个选项吧，容我想想。

**Comment by jasonpakio** [comment]
thanks~

**Comment by CXTretar** [comment]
@jasonpakio 已经定制了一个，你可以下载demo看一下

**Comment by jasonpakio** [comment]
好的  ~THANKS

**Comment by jasonpakio** [comment]
可不可以不要背景的2018，显示个白色也可以~~~~     ☺

**Comment by CXTretar** [comment]
年份 2018 可以通过 datepicker.hideBackgroundYearLabel = YES;来设置，你试一下
